creating directory for saved model if it does not exist
FileNotFoundError: [Errno 2] No such file or directory: 'saved_agent/best_agent.json'

Writing to file will crash if the folder does not exist. Added function to create directory if it does not exist